#!/bin/bash

ERRORS_FOUND=0

while read COMMIT_START COMMIT_END REFNAME
do
  echo "Start: $COMMIT_START"
  echo "End:   $COMMIT_END"
  echo "Ref.:  $REFNAME"

  # alteracoes
  FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $COMMIT_START $COMMIT_END 2> /dev/null)

  if [ $? -gt 0 ]
  then
    # novo branch
    FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $COMMIT_END 2> /dev/null)

    if [ $? -gt 0 ]
    then
      # provavelmente removendo branch
      continue
    fi
  fi

  for FILE in $FILES_CHANGED
  do
    if [ ${FILE: -4} == ".php" ]
    then
      echo -n "Checagem de sintaxe do arquivo: $FILE... "
      git show $COMMIT_END:$FILE | php -l

      if [ $? -gt 0 ]
      then
        ERRORS_FOUND=$((ERRORS_FOUND + 1))
      fi
    fi
  done
done

if [ $ERRORS_FOUND -gt 0 ]
then
  echo "Erros de sintaxe PHP encontrados, push cancelado. Verifique o log para identificacao do problema"

  exit 1
fi